name: testing

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '**.php'
      - 'composer.*'
  pull_request:
    paths:
      - '**.php'
      - 'composer.*'

jobs:
  testing:
    name: PHP 8.1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug

      - name: Get composer cache directory
        run: echo "COMPOSER_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --no-progress --no-interaction

      - name: Check runtime dependencies
        run: composer check-platform-reqs

      - name: Run Composer Validate
        run: composer validate --strict

      - name: Run Composer Normalize
        run: composer normalize --dry-run

      - name: Run static analysis
        run: vendor/bin/phpstan --memory-limit=-1 --verbose

      - name: Run coding style checker
        run: vendor/bin/pint -v --test

      - name: Run tests
        run: vendor/bin/pest
